AWSTemplateFormatVersion: '2010-09-09'
Description: Scheduler Agent Lambda CloudFormation Template

Resources:

  GamedayArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-gameday-artifacts"
      VersioningConfiguration:
        Status: Enabled

Outputs:
  S3BucketforGameday:
    Value: !Ref GamedayArtifactsBucket
    Description: ARN of the S3 bucket.