AWSTemplateFormatVersion: '2010-09-09'
Description: Scheduler Agent Lambda CloudFormation Template

Resources:

  # GamedayArtifactsBucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: !Sub "${AWS::StackName}-gameday-artifacts"
  #     VersioningConfiguration:
  #       Status: Enabled

  # GoogleCalendarSecrets:
  #   Type: AWS::SecretsManager::Secret
  #   Properties:
  #     Name: scheduler-agent-gcalendar-secret
  #     Description: Credentials and token secrets of the Google Calendar account used in GenAI gameday series.
  #     SecretString: '{"username":"admin","password":"SuperSecret123!"}' ## Needs Update

  GamedaySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: gameday-sns-topic-new

  SchedulerAgnetLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: gameday-scheduler-agent-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: gameday-lambda-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # - Effect: Allow
              #   Action:
              #     - secretsmanager:GetSecretValue
              #   Resource: !Ref GoogleCalendarSecrets
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/gameday-scheduler-agent:*"
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref GamedaySNSTopic

  SchedulerAgentLambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: scheduler-agent-lambda-layer
      Description: Lambda layer with all the import modules used by the scheduler agent lambda function
      Content:
        S3Bucket: rk-gameday-bucket ## Needs update
        S3Key: scheduler-lambda-layer.zip  ## Needs update
      CompatibleRuntimes:
        - python3.13
      CompatibleArchitectures:
        - x86_64

  SchedulerAgentLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: gameday-scheduler-agent
      Architectures: 
        - x86_64
      Runtime: python3.13
      Handler: lambda_function.lambda_handler
      Role: !GetAtt SchedulerAgnetLambdaExecutionRole.Arn
      Code:
        S3Bucket: rk-gameday-bucket  ## Needs Update
        S3Key: scheduler-lambda.zip ## Needs update
      Layers:
        - !Ref SchedulerAgentLambdaLayer
      Timeout: 60
      MemorySize: 128
      Environment:
        Variables: ## Needs update on all ENV vaiable values
          AWS_REGION_NAME: !Ref "AWS::Region"
          AWS_SECRET_NAME: scheduler-agent-gcalendar-secret
          BOOTSTRAP_ENDPOINT: <bootstrap-server-endpoint>
          KAFKA_API_KEY: <kafka-api-key>
          KAFKA_API_SECRET: <kafka-api-secret>
          ORGANIZER: <organizer>
          SCHEMA_REGISTRY_ENDPOINT: <schema-registry-endpoint>
          SCHEMA_REGISTRY_API_KEY: <schema-registry-api-key>
          SCHEMA_REGISTRY_API_SECRET: <schema-registry-api-secret>
          TOPIC_NAME: scheduler_agent_response
          SNS_ARN: !Ref GamedaySNSTopic

Outputs:
  SchedulerAgentLambdaFunctionName:
    Value: !Ref SchedulerAgentLambdaFunction
    Description: ARN of the Scheduler Agent Lambda function

  # GoogleCalendarSecretsName:
  #   Value: !Ref GoogleCalendarSecrets
  #   Description: ARN of the Google Calendar Secrets in the Secret Manager

  SchedulerAgentLambdaLayerName:
    Value: !Ref SchedulerAgentLambdaLayer
    Description: ARN of Lambda layer created for Scheduler Agent Lambda Fn.

  SNSTopicName:
    Value: !Ref GamedaySNSTopic
    Description: ARN of the SNS topic created for Scheduler lambda fn to publishs.

  